### ISSUE TITLE
license

### ISSUE THREAD

**Issue by wilfried18** [theshid/ClipBoard-Manager#1]
Hello
I want you to know the license of your application. 
I'd like to test your application but I can't find an apk file.
I know that on GitHub it's not mandatory, but a compiled apk will have a better chance of being used than if it's up to us to compile it.
Thank you

**Comment by theshid** [comment]
Hello Wilfried
What do you mean by the licence of my application? As if you can use it? I'm kinda new into programming and Github so I'm not awareof everything.
I just uploaded the apk, you can find it in the release section, thanks for mentionning it, if you have any ideas after testing the app feel free to let me know. 
PS: Je suis bilingue, n'hésites pas à écrire en français si c'est plus facile pour toi.

**Comment by wilfried18** [comment]
@theshid Merci en effet je suis français. 
Je voulait savoir la license de ton application android sois apache GNU ou copyright ou Cc by etc
Je suis désolé je viens juste de trouver l'APk
Quand je veux l'utiliser et que je met activate service. 
Sa me donne 
![Screenshot_2020-03-05-01-12-42-406_com miui bugreport](https://user-images.githubusercontent.com/6059645/75935419-6d8c7300-5e7f-11ea-87ef-342023593a74.jpg)
Je ne sais pas ce que tu peux faire
Merci

**Comment by theshid** [comment]
D'accord je vais regarder ça, pourrais tu me donner la version d'Android que tu utilises? (le nom et le API) , et c'est dès que tu actives le service que ça plante ou quelque temps après?

**Comment by wilfried18** [comment]
@theshid comme je vois pas le API je t fait une capture ecran.
 Android 10 et oui c'est bien a son activation (peux etre du a android 10)

**Comment by theshid** [comment]
J'ai pu corrigé l'erreur mais malheuresement il y a un second problème dû à android 10

> As part of a focus on privacy, Android 10 brought restrictions on apps accessing the clipboard. Now, only the app that currently has focus or the default input method editor (such as the keyboard) can access that data. If you try to access it under any other circumstance, the system will behave as if the clipboard was empty.

> 

Donc même si le service est activé les données du clipboard ne sont pas copiés. Je suis entrain de voir si il ya moyen d'utiliser le clipboardManager tout en respectant les nouvelles règles introduite pour android 10.

**Comment by wilfried18** [comment]
Merci @theshid  pour ton aide et réactivité car c'est important quand on a des souci de mémoire

**Comment by theshid** [comment]
De rien ;)
